# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文必须问MarkDown格式', verbose_name='内容'),
        ),
    ]
